version: 0.0
os: linux
files:
  - source: /pom.xml
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: terraform-client/install_dependencies
      timeout: 300
      runas: root
    - location: terraform-client/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: terraform-client/stop_server
      timeout: 300
      runas: root
